"""
Core data models shared across the linter.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from enum import Enum


class Severity(str, Enum):
    CRITICAL = "critical"
    HIGH     = "high"
    MEDIUM   = "medium"
    LOW      = "low"


class Status(str, Enum):
    PASS    = "pass"
    FAIL    = "fail"
    WARN    = "warn"
    SKIP    = "skip"


@dataclass
class CheckRule:
    """A single check rule loaded from the custom profile."""
    id: str
    name: str
    description: str
    severity: Severity
    category: str
    remediation: str                    # static remediation hint
    enabled: bool = True
    # optional override per environment
    env_overrides: Dict[str, Any] = field(default_factory=dict)
    # JSONPath / field selectors used by the check engine
    selectors: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ResourceContext:
    """Metadata about the K8s resource being checked."""
    kind: str
    name: str
    namespace: str
    source: str                         # "cluster" | "manifest"
    raw: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Finding:
    """Result of a single check against a single resource."""
    rule_id: str
    rule_name: str
    severity: str
    status: str                         # pass | fail | warn | skip
    category: str
    resource: ResourceContext
    detail: str = ""                    # human-readable detail of what was found
    remediation_static: str = ""        # from profile
    remediation_ai: str = ""            # generated by AI agent
    evidence: Dict[str, Any] = field(default_factory=dict)


@dataclass
class AuditResults:
    """Aggregated results from a full lint run."""
    namespace: str
    source: str
    profile_name: str
    findings: List[Finding] = field(default_factory=list)
    resources_scanned: int = 0
    checks_run: int = 0
    score: float = 0.0
    grade: str = "F"
    summary: Dict[str, int] = field(default_factory=dict)
    ai_summary: str = ""                # AI-generated executive summary

    def compute_score(self) -> None:
        """Compute weighted score and grade from findings."""
        weight_map = {
            Severity.CRITICAL: 4,
            Severity.HIGH:     2,
            Severity.MEDIUM:   1,
            Severity.LOW:      0.5,
        }
        total_weight = 0.0
        pass_weight  = 0.0
        counts = {"pass": 0, "fail": 0, "warn": 0, "skip": 0}

        for f in self.findings:
            w = weight_map.get(f.severity, 1)
            total_weight += w
            if f.status == Status.PASS:
                pass_weight += w
            counts[f.status] = counts.get(f.status, 0) + 1

        self.summary = counts
        self.score = round((pass_weight / total_weight * 100) if total_weight else 0, 1)

        if self.score >= 90:
            self.grade = "A"
        elif self.score >= 80:
            self.grade = "B"
        elif self.score >= 65:
            self.grade = "C"
        elif self.score >= 50:
            self.grade = "D"
        else:
            self.grade = "F"
